name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build project
        if: ${{ false }}
        run: ./gradlew clean build
        
      - name: Print docker version
        run: docker images
        
      - name: Run tests
        run: ./gradlew test --info
